use_default_settings:
  engines:
    keep_only:
      - google
      - bing
      - duckduckgo
      - wikipedia
      - github
      - youtube_noapi
      - reddit
      - arxiv
      - openstreetmap

general:
  debug: false
  instance_name: "SearXNG"
  privacypolicy_url: false
  donation_url: false
  contact_url: false
  enable_metrics: false

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "all"
  formats:
    - html
    - json

server:
  secret_key: "4f0158d9fc0a9750d55e338fef1092f078b11ee6b84d9139bf203dcd845b7602"
  limiter: false
  image_proxy: true
  port: 8080
  bind_address: "0.0.0.0"
  base_url: false

valkey:
  url: redis://searxng-valkey:6379/0

ui:
  default_locale: "vi"

enabled_plugins:
  - 'Hash plugin'
  - 'Self Information'
  - 'Tracker URL remover'
