# Disable all bot detection and rate limiting

[botdetection]
ipv4_prefix = 32
ipv6_prefix = 48
trusted_proxies = ['0.0.0.0/0', '::/0']

[botdetection.ip_limit]
filter_link_local = false
link_token = false

[botdetection.ip_lists]
block_ip = []
pass_ip = ['0.0.0.0/0', '::/0']
pass_searxng_org = false

[botdetection.http_accept]
http_accept_encoding_list = []
http_accept_language_list = []

[botdetection.http_user_agent]
crawlers_user_agents = []
